DATA SEGMENT 
    msg1 db 10,13, 'HELLO WORLD$'
DATA ENDS
CODE SEGMENT 
START:    
    ASSUME CS:CODE,DS:DATA
    MOV AX,DATA
    MOV DS,AX
    LEA DX,msg1
    MOV AH,09H
    INT 21H
    
    MOV AH,4CH
    MOV AL,00H
    INT 21H
END START
CODE ENDS    
